addons:
  apt:
    packages:
      - python-pygments

    install:
      - rm -rf public || exit 0

    script:
      - ./binaries/hugo

    deploy:
      provider: pages
    skip_cleanup: true
    local_dir: public
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
