baseURL = "https://kopikonfig.com/"
languageCode = "en-us"
title = "Geek kang kopas"
pygmentsstyle= "monokai"

theme = "hugo-theme-novela"

paginate = 6

[social]
twitter= "https://twitter.com/sandiko_r"
github= "https://github.com/mh4nx7net"
linkedin= "https://www.linkedin.com/in/raqhni-sandiko-16b975175"
instagram = "https://instagram.com/rsandi18"
dribbble = "#"
youtube = "https://youtube.com"

[taxonomies]
author = "authors"
